shrinkwrap/resolver

- .travis.yml
- impl-maven-archive/pom.xml
- impl-maven/pom.xml
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/ManualWagonProvider.java
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/ShrinkWrapResolverServiceLocator.java
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/MavenModelResolver.java
- maven-plugin/pom.xml
- pom.xml
Updated versions of aether, maven and some plexus libs. 
Modified the implementation to suit the changes of dependencies. 
Added new aether-transport-wagon module introduced in aether-0.9.0.M3 and changed aether-connector-wagon module to aether-connector-basic
Added com.google.guava:guava dependency because it's functionality is used in new methods of the class:
impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/MavenModelResolver.java
> [SHRINKRES-220] updated versions of aether, maven and some plexus libs

- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/ConfigurableMavenWorkingSessionImpl.java
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/SettingsManager.java
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/task/ConfigureSettingsFromFileTask.java
- impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/InvalidSettingsTestCase.java
- impl-maven/src/test/resources/profiles/settings-invalid.xml
Previously, when the Maven.configureResolver() was called, the default settings.xml was immediately loaded - this is not always appropriate - see: https://developer.jboss.org/message/936418
I've created two new classes:
SettingsManager.java
- is a manager for all operation related to an instance of the Settings
- handles the (re)generation of the Settings and keeps the instance
ConfigurableMavenWorkingSessionImpl.java
- handles all operation related to DefaultRepositorySystemSession that doesn't need to have created an instance of the DefaultRepositorySystemSession for its calling
- handles the (re)generation of the DefaultRepositorySystemSession and  keeps the instance
- this kind of methods have been moved from MavenWorkingSessionImpl class
I've attached also the test case
> SHRINKRES-226 Loading of the settings.xml configuration has been postponed

- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/decrypt/MavenPlexusCipher.java
- impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/MavenPlexusCipherTestCase.java
see: 
[SHRINKRES-231 - MavenPlexusCipher matches string that doesn't represent a cipher](https://issues.jboss.org/browse/SHRINKRES-231)
[SHRINKRES-227 - ShrinkWrap Maven Resolver doesn't support env vars in settings.xml](https://issues.jboss.org/browse/SHRINKRES-227)
I've created two phased verification:
1.phase matches a cipher within {} that has some preceding string except:
${bla}
\{bla}
2. phase matches a cipher within {} without having any preceding string (starting on the beginning of line)
> SHRINKRES-231 Modified regex to match correct ciphers, added test case

- gradle/impl-gradle-embedded-archive/pom.xml
- gradle/impl-gradle/pom.xml
http://repo.jfrog.org/artifactory/repo no longer works
Not sure if it's temporary hick up, but does not seem so.
> Fix jfrog's gradle repo URL

- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/DefaultSettingsXmlLocationTestCase.java
replaceAll() takes a regex, but we do not provide one. Use replace()
instead, which despite its name also replaces all matching substrings.
> Fix removeDoubledSeparator()

- README.asciidoc
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/PomEquippedResolveStageBase.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/PomEquippedResolveStageBaseImpl.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/ArtifactDependenciesTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/OfflineRepositoryTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/PomDependenciesUnitTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/PomFilteringUnitTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/PomTransitivesUnitTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/ProfilesUnitTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/SpringTransitivityTestCase.java
- maven/maven-plugin/src/it/context-propagation/src/test/java/org/jboss/shrinkwrap/resolver/plugin/test/PluginIntegrationTestCase.java
Asking for runtime dependencies should not include compile dependencies as these scopes are distinct.
This PR is more or less an RFC as I don't believe it would be merged as-is as it changes the current behavior. While I'm maybe missing something, I believe also the other convenience methods to import dependencies partly do the wrong thing.
Any comment as to why that is?
> Fix convenience methods to import dependencies

- maven/impl-maven/src/main/resources/META-INF/services/org.jboss.shrinkwrap.resolver.spi.format.FormatProcessor
- spi/src/main/java/org/jboss/shrinkwrap/resolver/spi/format/FileFormatProcessor.java
- spi/src/main/java/org/jboss/shrinkwrap/resolver/spi/format/InputStreamFormatProcessor.java
- spi/src/main/java/org/jboss/shrinkwrap/resolver/spi/format/PathFormatProcessor.java
- spi/src/main/java/org/jboss/shrinkwrap/resolver/spi/format/URLFormatProcessor.java
https://issues.jboss.org/browse/SHRINKRES-281
Hi, I thought that'd be a good addition in the age of NIO :)
I've tested it with my own project, but I wasn't sure where to add a test in ShrinkWrap itself. Happy to add one if you can give me some directions. Also I followed the example of the existing processors and registered the new one in the services file in the _impl-maven_ module. Is anything else needed to make it work for Gradle, too?
> SHRINKRES-281 Format processor for java.nio.file.Path

- maven/api-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/embedded/pom/equipped/ConfigurationStage.java
- maven/impl-maven-embedded/src/it/cube-gradle-sample/gradle-sample/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/pom/equipped/PomEquippedEmbeddedMavenRunningWithAlternateTestCase.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/pom/equipped/ConfigurationStageImpl.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/pom/equipped/PomEquippedEmbeddedMavenImpl.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/ConfigurationStageTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/pom/equipped/PomEquippedEmbeddedMavenRunningWithAlternateTestCase.java
Sometimes it is required to use a POM file different from the parent pom file or a pom file in another modules for executing Maven goals. 
A feature equivalent to setting "-f or --file" parameter from CLI in embedded maven was missing.
This PR resolves this by providing a means of resetting the pom.xml file.
> Introduces functionality to set an alternate POM file in embedded maven.

- README.asciidoc
- maven/api-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/embedded/DistributionStage.java
- maven/impl-maven-embedded/pom.xml
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/BuildStageImpl.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/DistributionStageImpl.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/BuildOutputTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/DefaultMavenVersionTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/MavenDownloadsTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/invoker/equipped/InvokerEquippedEmbeddedMavenForJarSampleTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/pom/equipped/PomEquippedEmbeddedMavenForJarSampleTestCase.java
By default, it uses hard-coded Maven binary version(corresponding to Maven dependency) - which is `3.3.9`.
Added another method `useLocalInstallation` to set that the binary available on PATH should be used.
> EmbeddedMaven - default version

- README.asciidoc
built is the past tense of build.  You refer to the artifact generated by Maven to be a build.  
I love this project!  Much easier to create complex test objects to deploy.
> fixing tense of the word build

- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/DistributionStageImpl.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/FileExtractor.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/FileExtractorTestCase.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/MavenExtractionTestCase.java
We should avoid synchronize locking on String literal.
Ref - 
https://stackoverflow.com/questions/18206301/effect-of-synchronizedstatic-variable
https://www.javalobby.org/java/forums/t96352.html
http://javarevisited.blogspot.in/2011/04/synchronization-in-java-synchronized.html - Point 20
This fix won't reproduce https://github.com/arquillian/smart-testing/issues/293
> fix: Improved logic for extraction

- .travis.yml
- maven/impl-maven-embedded/pom.xml
Based on #138 by @apupier + fix/workaround for some tests failing with:
```
java.lang.IllegalStateException: Maven application directory was not specified, and ${maven.home} is not provided in the system properties. Please specify at least on of these.
```
`org.jboss.shrinkwrap.resolver.api.maven.embedded.DistributionStage.useLocalInstallation()` (which is used in the affected tests) says:
> Use local Maven installation that is available on your PATH.
I don't see how this is supposed to work. Maven _is_ on the `PATH` and still this doesn't work.
> fix(SHRINKRES-296): update dist for newer JDK7 and fix/workaround maven.home problem

- README.asciidoc
- maven/impl-maven-embedded/pom.xml
- maven/impl-maven/pom.xml
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/aether/ClasspathWorkspaceReader.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/aether/ClassPathScanningTestCase.java
- maven/impl-maven/src/test/resources/poms/test-ordinary/child/pom.xml
- maven/impl-maven/src/test/resources/poms/test-ordinary/pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision-custom/child/pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision-custom/child/target/my-flat-pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision-custom/pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision/child/.flattened-pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision/child/pom.xml
- maven/impl-maven/src/test/resources/poms/test-revision/pom.xml
- pom.xml
by preferring the output of flatten-maven-plugin over the regular pom.xml
which just has a "useless" placeholder like ${revision} as the version.
**Some notes about this approach:**
There is already a TODO note in `ClasspathWorkspaceReader.createFoundArtifact(File)` about whether it would be better to load the pom (and its parents) "properly" via Maven.
This might have also been a possible solution, but I am not sure whether such a heavy lifting should be done there.
The note regarding "cycle in graph reconstruction" also scared me off a bit, to be honest.
Furthermore, a `revision` property does not need to defined in the pom at all (AFAIK). It can also be passed in via `-Drevision=...`. Parsing the entire Maven model would not help in that case.
My first approach was to completely swap …
> fix(SHRINKRES-299): Support "Maven CI Friendly Versions"

- pom.xml
Although `system-rules 1.19.0` being released already, #142 upgraded from `1.16.0` to just `1.17.0` due to a test failure on JDK7 with `> 1.17.0`: https://github.com/shrinkwrap/resolver/pull/142#issuecomment-568019712
Later, that problem could not be reproduced anymore, see #143. 
So it seems we can update right away.
> chore: update system-rules to 1.19.0

- .travis.yml
- pom.xml
As discussed here: https://github.com/shrinkwrap/resolver/commit/2018e1bb704a0e4593f65ca69fd955f50eb58bfb#commitcomment-36651197
> chore: bring back jdk7 Travis build

- .travis.yml
would be great to run with `-fae` too but lets at least save some scrolling when looking at failing travis build
> chore(travis): enables batch mode for mvn build

- .travis.yml
- impl-gradle-embedded-archive/pom.xml
- impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java
Hi @MatousJobanek @bartoszmajsak, I'm not sure who's in charge of ShrinkWrap Resolver these days, but I'd like this HTTP -> HTTPS fix to be backported to the 2.2.x branch, because updating to latest 3.1.4 in Thorntail proves very difficult (I found one breaking change, but even after fixing that, things still don't work as they should).
The other commit, JFrog repo URL change, is necessary to make the project build. I found that `mvn clean install` works fine with Maven 3.3.9; when using Maven 3.6.3, some of the Maven plugin tests fail because of binary incompatible change in Aether or something like that. I think that's probably expected, considering this comment in `/pom.xml`: `Aether version must be the same as used in Maven in order for plugin to work`.
I think it should be perfectly …
> backport some important fixes to the 2.2.x branch

- gradle/impl-gradle/pom.xml
https://issues.redhat.com/browse/SHRINKRES-308
> SHRINKRES-308 Gradle cannot be downloaded from https://repo.jfrog.org/artifactory/gradle

- bom/pom.xml
The "org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-bom" links to the shrinkwrap repository. I assume that this is the reason why dependabot showed the commit history of the shrinkwrap repository instead of the resolver changelog, see https://github.com/arquillian/arquillian-extension-warp/pull/142 for a sample.
> Fixed links to resolver repository in BOM

- maven/impl-maven-archive/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/importer/ConfiguredMavenImporterTestCase.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/MavenManagerBuilder.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/PackageDirHelperTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/OfflineRepositoryTestCase.java
https://issues.redhat.com/browse/SHRINKRES-319
> [SHRINKRES-319] Resolve deprecated API usage

- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/PackagingType.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenCoordinateImpl.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenGABaseImpl.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/filter/ScopeFilter.java
- maven/impl-maven-archive/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/plugins/Validate.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/ConfigurableMavenResolverSystemImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/coordinate/MavenDependencyImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/util/Validate.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/ClassifiersTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/ClasspathWorkspaceReaderTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/DependencyDepthTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/util/ValidationUtil.java
https://issues.redhat.com/browse/SHRINKRES-320
> [SHRINKRES-320] Resolve control flow issues

- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/PackagingType.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/ScopeType.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenCoordinateImpl.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenCoordinates.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenDependencies.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenGABaseImpl.java
- maven/api-maven/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/filter/RejectDependenciesFilter.java
- maven/api-maven/src/test/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenCoordinateImplTestCase.java
- maven/impl-maven-archive/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/plugins/CompilerPluginConfiguration.java
- maven/impl-maven-archive/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/plugins/ConfigurationUtils.java
- maven/impl-maven-archive/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/plugins/MavenArchiveConfiguration.java
- maven/impl-maven-archive/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/archive/plugins/Validate.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/BuildTrigger.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenArtifactInfoImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenVersionRangeResultImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/ResolveStageBaseImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/MavenSettingsBuilder.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/convert/MavenConverter.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/decrypt/MavenPlexusCipher.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/decrypt/MavenSecurityDispatcher.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/pom/ParsedPomFileImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/task/ConfigureSettingsFromFileTask.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/util/FileUtil.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/util/Validate.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/api/maven/coordinate/MavenDependencyImplTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/RepositoryAuthTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/util/ValidationUtil.java
- maven/maven-plugin/src/main/java/org/jboss/shrinkwrap/resolver/plugin/DependencyTreeMojo.java
- spi/src/main/java/org/jboss/shrinkwrap/resolver/spi/loader/SpiServiceLoader.java
https://issues.redhat.com/browse/SHRINKRES-321
> [SHRINKRES-321] Resolve code style issues

- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/PostResolutionFilter.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/AsMavenResolvedArtifactTestCase.java
- maven/impl-maven/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/integration/PomDependenciesUnitTestCase.java
https://issues.redhat.com/browse/SHRINKRES-282
https://issues.redhat.com/browse/SHRINKRES-305
POMs now can be resolved by specifying pom in the resolution form and using withoutTransitivity
> [SHRINKRES-305] [SHRINKRES-282] Resolve just a pom.xml

- maven/impl-maven-embedded/pom.xml
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/BinaryDownloader.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/FileExtractor.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/FilePermission.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/MarkerFileHandler.java
- maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/PermissionsUtil.java
- maven/impl-maven-embedded/src/test/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/MavenDownloadsTestCase.java
- pom.xml
https://issues.redhat.com/browse/SHRINKRES-343
> [SHRINKRES-343] Remove Arquillian Spacelift dependency

- .github/dependabot.yml
Due to an error in Dependabot we got multiple duplicate PRs for a single dependency. We have to remove the directories for now and watch whether the fix has been provided
https://github.com/dependabot/dependabot-core/issues/10415
https://github.com/dependabot/dependabot-core/issues/10340
> chore: replace directories in dependabot

- README.md
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/MavenSettingsBuilder.java
Maven team has changed how project-local pom is organized slightly.
`-consumer.pom` files have been renamed to just `.pom`
This PR fixes problems associated with that change
Added `org.jboss.shrinkwrap.resolver.maven.ignoreDecryptionProblems` system property
to ignore security issues since maven 4 completely changed the format of encrypted passwords
> [SHRINKRES-354] update to keep track of changes in maven 4-rc-1

- README.md
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java
- maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/bootstrap/MavenRepositorySystem.java
Maven release 4.0.0-rc-2 changed how consumer POM is generated.
new option `maven.consumer.pom=true` is necessary to make ShrinkWrap work prior to the PR,
and take full advantage of maven 4 features in the future.
> chore: keep updated with maven 4 rc-2 consumer pom changes
